### ISSUE TITLE
you should maybe fix gitignore so i made a issue but but idk how to fix it 

### ISSUE THREAD

**Issue by JoeyE2** [Zordlan/SkyClientBot#13]

**Comment by Zordlan** [comment]
cant fix it if i dont know whats broken

**Comment by JoeyE2** [comment]
there was an entire folder ytou thought you gitignored and its wasant idk what is was

**Comment by Zordlan** [comment]
everything that should be gitignored is gitignored

if you think something should be gitignored, just type its name in the .gitignore file

like, if the folder "hi" should be gitignored, just add the word "hi" to the gitignore
